# Generated by Django 6.0.1 on 2026-02-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('number', 'Number Input'), ('dropdown', 'Dropdown Selection')], default='text', max_length=20)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for dropdown')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
