# Generated by Django 6.0.1 on 2026-02-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_surveyresponse_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='household_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
